import { existsSync } from "fs";
import type { RequestHandler } from "express";
import mime from "mime-types";
import path from "path";
import process from "process";
import { z } from "zod";

import { UploadFile, images, music } from "./upload-internal.js";
import { GetS3File } from "../../infra/s3.js";
import { BadRequestError, NotFoundError } from "../../lib/errors.js";
import { appConfig } from "../../config/app.js";

const SAFE_FILENAME = /^[A-Za-z0-9._-]+\.(png|jpe?g|gif|webp)$/i;

export const assetFilenameParamsSchema = z.object({
  filename: z.string().trim().regex(SAFE_FILENAME, "Invalid filename"),
});

type AssetFolder = "images" | "pfps";
type UploadKind = "image" | "music";

type StoredAsset =
  | {
      kind: "local";
      path: string;
    }
  | {
      kind: "buffer";
      buffer: Buffer;
      contentType: string;
    };

function getUploadHandler(kind: UploadKind) {
  return kind === "image" ? images : music;
}

const multipartErrors = new Map([
  ["Multipart: Boundary not found", "Missing multipart boundary. Send multipart/form-data with the boundary generated by your form-data client."],
  ["Unexpected end of form", "Incomplete multipart upload. The request body must include the complete file and closing boundary."],
  ["Unexpected end of file", "Incomplete uploaded file. Send the complete file before closing the request."],
  ["Malformed part header", "Malformed multipart headers. Each file part must include Content-Disposition with a field name and filename."],
]);

const uploadLimitErrors = new Map([
  ["LIMIT_UNEXPECTED_FILE", 'Unexpected file field or extra file. Send exactly one file in the multipart field named "upload".'],
  ["LIMIT_PART_COUNT", "Too many multipart parts."],
  ["LIMIT_FILE_COUNT", "Too many uploaded files. Send exactly one file."],
  ["LIMIT_FIELD_KEY", "Multipart field name is too long."],
  ["LIMIT_FIELD_VALUE", "Multipart field value is too large."],
  ["LIMIT_FIELD_COUNT", "Too many multipart fields."],
  ["MISSING_FIELD_NAME", "Multipart field name is missing."],
  ["INVALID_FIELD_NAME", "Invalid multipart field name."],
  ["LIMIT_FIELD_NESTING", "Multipart field name nesting is too deep."],
  ["LIMIT_FIELD_ARRAY_INDEX", "Multipart field array index is too large."],
]);

export function createUploadMiddleware(kind: UploadKind): RequestHandler {
  const uploader = getUploadHandler(kind);

  return (req, res, next) => {
    uploader.single("upload")(req, res, (err) => {
      if (!err) {
        next();
        return;
      }

      if (err.code === "LIMIT_FILE_SIZE") {
        const limit = kind === "music"
          ? appConfig.api.limits.uploadMusicBytes
          : appConfig.api.limits.uploadImageBytes;
        next(new BadRequestError(`File is too large. Maximum upload size is ${limit / (1024 * 1024)} MiB.`));
        return;
      }

      if (err.message === "Invalid file type") {
        next(new BadRequestError(kind === "music"
          ? "Unsupported audio format. Please upload an MP3, WAV, or OGG file."
          : "Unsupported image format. Please upload a JPEG, PNG, GIF, or WebP file."));
        return;
      }

      const message = uploadLimitErrors.get(err.code) ?? multipartErrors.get(err.message);
      if (message) {
        next(new BadRequestError(message));
        return;
      }

      next(err);
    });
  };
}

export async function handleUploadedFile(req: Parameters<typeof UploadFile>[0], res: Parameters<typeof UploadFile>[1]) {
  await UploadFile(req, res);
}

export async function getStoredAssetByFilename({
  folder,
  filename,
}: {
  folder: AssetFolder;
  filename: string;
}): Promise<StoredAsset> {
  const assetPath = path.join(process.cwd(), "public", folder, filename);

  if (existsSync(assetPath)) {
    return {
      kind: "local",
      path: assetPath,
    };
  }

  const fileBuffer = await GetS3File(folder, filename);
  if (fileBuffer) {
    return {
      kind: "buffer",
      buffer: fileBuffer,
      contentType: mime.lookup(filename) || "application/octet-stream",
    };
  }

  throw new NotFoundError("Image not found");
}

