SELECT setval(
  pg_get_serial_sequence('"TagCategory"', 'id'),
  COALESCE((SELECT MAX("id") FROM "TagCategory"), 1),
  EXISTS (SELECT 1 FROM "TagCategory")
);

SELECT setval(
  pg_get_serial_sequence('"Tag"', 'id'),
  COALESCE((SELECT MAX("id") FROM "Tag"), 1),
  EXISTS (SELECT 1 FROM "Tag")
);

INSERT INTO "TagCategory" ("name", "priority", "createdAt", "updatedAt")
VALUES
  ('General', 9999, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Development', 101, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Art', 91, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Sound', 81, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Game Engines / Frameworks', 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Art Software', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Music Software', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Storefronts', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("name") DO NOTHING;

INSERT INTO "Tag" (
  "name",
  "description",
  "autoRegex",
  "alwaysAdded",
  "priority",
  "modOnly",
  "icon",
  "createdAt",
  "updatedAt",
  "categoryId",
  "gameTag",
  "postTag"
)
SELECT
  taxonomy."name",
  taxonomy."description",
  taxonomy."autoRegex",
  taxonomy."alwaysAdded",
  taxonomy."priority"::"Priority",
  taxonomy."modOnly",
  taxonomy."icon",
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
  category."id",
  taxonomy."gameTag",
  taxonomy."postTag"
FROM (
  VALUES
  ('Art Software', '3dsMax', 'Artwork made with Autodesk 3ds Max', '\b(?:3ds[-\s]?max|3d[-\s]+studio[-\s]+max)\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/3dsmax.svg', TRUE, TRUE),
  ('Music Software', 'AbletonLive', 'Music made with Ableton Live', '\bableton(?:[-\s]+live)?\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/abletonlive.svg', TRUE, TRUE),
  ('Art Software', 'AffinityDesigner', 'Artwork made with Affinity Designer', '\baffinity[-\s]+designer\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/affinitydesigner.png', TRUE, TRUE),
  ('Storefronts', 'AppStore', 'Games available through the Apple App Store', '\b(?:apple[-\s]+)?app[-\s]+store\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/appstore.png', FALSE, TRUE),
  ('Music Software', 'Ardour', 'Music made with Ardour', '\bardour\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/ardour.png', TRUE, TRUE),
  ('Art', 'Art', NULL, '\bart\b', FALSE, 'MEDIUM', FALSE, '/images/tags/art.png', FALSE, TRUE),
  ('Art Software', 'Aseprite', NULL, 'aseprite', FALSE, 'HIGH', FALSE, '/images/tags/aseprite.png', TRUE, TRUE),
  ('Music Software', 'Audacity', 'Audio made with Audacity', '\baudacity\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/audacity.png', TRUE, TRUE),
  ('Music Software', 'BeepBox', 'Music made with BeepBox', '\bbeep[-\s]?box\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/beepbox.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'Bevy', NULL, 'bevy', FALSE, 'HIGH', FALSE, '/images/tags/bevy.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'Bitsy', NULL, 'bitsy', FALSE, 'HIGH', FALSE, '/images/tags/bitsy.png', TRUE, TRUE),
  ('Music Software', 'BitwigStudio', 'Music made with Bitwig Studio', '\bbitwig(?:[-\s]+studio)?\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/bitwigstudio.png', TRUE, TRUE),
  ('Art Software', 'Blender', NULL, 'blender', FALSE, 'HIGH', FALSE, '/images/tags/blender.webp', TRUE, TRUE),
  ('Art Software', 'Blockbench', 'Artwork made with Blockbench', '\bblockbench\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/blockbench.png', TRUE, TRUE),
  ('Music Software', 'BoscaCeoil', 'Music made with Bosca Ceoil', '\bbosca[-\s]+ceoil\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/boscaceoil.png', TRUE, TRUE),
  ('Music Software', 'Cakewalk', 'Music made with Cakewalk', '\b(?:cakewalk[-\s]+by[-\s]+bandlab|cakewalk[-\s]+daw|made[-\s]+(?:in|with)[-\s]+cakewalk|using[-\s]+cakewalk)\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/cakewalk.svg', TRUE, TRUE),
  ('Game Engines / Frameworks', 'Clickteam', NULL, 'clickteam', FALSE, 'HIGH', FALSE, '/images/tags/clickteam.png', TRUE, TRUE),
  ('Art Software', 'ClipStudioPaint', 'Artwork made with Clip Studio Paint', '\bclip[-\s]+studio[-\s]+paint\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/clipstudiopaint.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'CocosCreator', 'Games made with Cocos Creator', '\bcocos[-\s]?creator\b', FALSE, 'MEDIUM', FALSE, NULL, TRUE, TRUE),
  ('Game Engines / Frameworks', 'Construct3', NULL, 'construct', FALSE, 'HIGH', FALSE, '/images/tags/construct.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'CryEngine', NULL, 'cryengine', FALSE, 'HIGH', FALSE, '/images/tags/cryengine.png', TRUE, TRUE),
  ('Music Software', 'Cubase', 'Music made with Cubase', '\bcubase\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/cubase.svg', TRUE, TRUE),
  ('General', 'D2Jam', NULL, '.*', TRUE, 'HIGH', FALSE, '/images/tags/d2jam.png', FALSE, TRUE),
  ('Game Engines / Frameworks', 'Defold', NULL, 'defold', FALSE, 'HIGH', FALSE, '/images/tags/defold.png', TRUE, TRUE),
  ('Development', 'Devlog', NULL, 'devlog', FALSE, 'HIGH', FALSE, '/images/tags/devlog.png', FALSE, TRUE),
  ('Art', 'DigitalArt', NULL, '(?:digital\s?)?art\b', FALSE, 'HIGH', FALSE, '/images/tags/digitalart.png', TRUE, TRUE),
  ('Storefronts', 'EpicGamesStore', 'Games available through the Epic Games Store', '\bepic(?:[-\s]+games)?[-\s]+store\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/epicgamesstore.png', FALSE, TRUE),
  ('Music Software', 'FamiStudio', 'Music made with FamiStudio', '\bfami[-\s]?studio\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/famistudio.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'FlaxEngine', 'Games made with Flax Engine', '\bflax(?:[-\s]+engine)?\b', FALSE, 'MEDIUM', FALSE, NULL, TRUE, TRUE),
  ('Game Engines / Frameworks', 'Flickgame', NULL, 'flickgame', FALSE, 'HIGH', FALSE, '/images/tags/flickgame.png', TRUE, TRUE),
  ('Music Software', 'FLStudio', 'Music made with FL Studio', '\bfl[-\s]+studio\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/flstudio.png', TRUE, TRUE),
  ('Music Software', 'FurnaceTracker', 'Music made with Furnace Tracker', '\bfurnace(?:[-\s]+tracker)?\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/furnacetracker.png', TRUE, TRUE),
  ('Development', 'GameAssets', NULL, 'asset', FALSE, 'HIGH', FALSE, '/images/tags/gameassets.png', FALSE, TRUE),
  ('Development', 'GameDesign', NULL, 'design', FALSE, 'MEDIUM', FALSE, '/images/tags/gamedesign.png', FALSE, TRUE),
  ('Development', 'Gamedev', NULL, '.*', FALSE, 'MEDIUM', FALSE, '/images/tags/console-controller.png', FALSE, TRUE),
  ('Storefronts', 'GameJolt', 'Games available through Game Jolt', '\bgame[-\s]+jolt\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/gamejolt.png', FALSE, TRUE),
  ('Game Engines / Frameworks', 'GameMaker', NULL, 'gamemaker', FALSE, 'HIGH', FALSE, '/images/tags/gamemaker.png', TRUE, TRUE),
  ('Music Software', 'GarageBand', 'Music made with GarageBand', '\bgarage[-\s]?band\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/garageband.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'GBStudio', NULL, 'gbstudio', FALSE, 'HIGH', FALSE, '/images/tags/gbstudio.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'GDevelop', NULL, 'gdevelop', FALSE, 'HIGH', FALSE, '/images/tags/gdevelop.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'geng', 'Games made with geng, a game engine for the Rust programming language', '\bgeng\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/geng.svg', TRUE, TRUE),
  ('Art Software', 'GIMP', 'Artwork made with GIMP', '\bgimp\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/gimp.svg', TRUE, TRUE),
  ('Art', 'GLSL', NULL, 'glsl', FALSE, 'HIGH', FALSE, '/images/tags/glsl.png', FALSE, TRUE),
  ('Game Engines / Frameworks', 'Godot', 'For things made in the Godot game engine', 'godot', FALSE, 'HIGH', FALSE, '/images/tag-icons/godot.svg', TRUE, TRUE),
  ('Storefronts', 'GOG', 'Games available through GOG', '\bgog(?:\.com)?\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/gog.svg', FALSE, TRUE),
  ('Storefronts', 'GooglePlay', 'Games available through Google Play', '\bgoogle[-\s]+play(?:[-\s]+store)?\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/googleplay.png', FALSE, TRUE),
  ('Game Engines / Frameworks', 'Haxe', NULL, 'haxe', FALSE, 'HIGH', FALSE, '/images/tags/haxe.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'HaxeFlixel', 'Games made with the HaxeFlixel engine', '\bhaxe[-\s]?flixel\b', FALSE, 'MEDIUM', FALSE, NULL, TRUE, TRUE),
  ('Storefronts', 'HumbleBundle', 'Games available through Humble Bundle', '\bhumble[-\s]+bundle\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/humblebundle.png', FALSE, TRUE),
  ('Art Software', 'Illustrator', 'Artwork made with Adobe Illustrator', '\b(?:adobe[-\s]+)?illustrator\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/illustrator.svg', TRUE, TRUE),
  ('General', 'ImIn', 'For posts announcing participation in the jam', '\b(i[''’]?m|i am)\s+in\b', FALSE, 'HIGH', FALSE, NULL, FALSE, TRUE),
  ('Art Software', 'Inkscape', 'Artwork made with Inkscape', '\binkscape\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/inkscape.svg', TRUE, TRUE),
  ('General', 'Introduction', NULL, 'intro', FALSE, 'MEDIUM', FALSE, '/images/tags/introduction.png', FALSE, TRUE),
  ('Storefronts', 'Itch', NULL, '(?:\bitch\.io\b|\bon\s+itch\b)', FALSE, 'MEDIUM', FALSE, '/images/tags/itch.png', FALSE, TRUE),
  ('Art Software', 'Krita', 'Artwork made with Krita', '\bkrita\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/krita.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'libGDX', NULL, 'libgdx', FALSE, 'HIGH', FALSE, '/images/tag-icons/libgdx.svg', TRUE, TRUE),
  ('Art Software', 'LibreSprite', 'Artwork made with LibreSprite', '\blibre[-\s]?sprite\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/libresprite.png', TRUE, TRUE),
  ('Music Software', 'LMMS', 'Music made with LMMS', '\blmms\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/lmms.png', TRUE, TRUE),
  ('Music Software', 'LogicPro', 'Music made with Logic Pro', '\blogic[-\s]+pro\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/logicpro.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'Love2D', NULL, 'love', FALSE, 'HIGH', FALSE, '/images/tags/love.png', TRUE, TRUE),
  ('Art', 'LowPoly', NULL, 'lowpoly', FALSE, 'HIGH', FALSE, '/images/tags/lowpoly.png', TRUE, TRUE),
  ('Art Software', 'MagicaVoxel', 'Artwork made with MagicaVoxel', '\bmagica[-\s]?voxel\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/magicavoxel.png', TRUE, TRUE),
  ('Art Software', 'Maya', 'Artwork made with Autodesk Maya', '\b(?:autodesk[-\s]+)?maya\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/maya.svg', TRUE, TRUE),
  ('General', 'Memes', NULL, 'meme', FALSE, 'HIGH', FALSE, '/images/tags/meme.png', FALSE, TRUE),
  ('Storefronts', 'MicrosoftStore', 'Games available through the Microsoft Store', '\bmicrosoft[-\s]+store\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/microsoftstore.png', FALSE, TRUE),
  ('Game Engines / Frameworks', 'MonoGame', 'Games made with the MonoGame framework', '\bmono[-\s]?game\b', FALSE, 'MEDIUM', FALSE, NULL, TRUE, TRUE),
  ('Music Software', 'MuseScore', 'Music made with MuseScore', '\bmuse[-\s]?score\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/musescore.png', TRUE, TRUE),
  ('Sound', 'Music', NULL, 'music', FALSE, 'MEDIUM', FALSE, '/images/tags/music.png', FALSE, TRUE),
  ('Storefronts', 'Newgrounds', 'Games available through Newgrounds', '\bnewgrounds\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/newgrounds.png', FALSE, TRUE),
  ('Storefronts', 'NintendoEShop', 'Games available through Nintendo eShop', '\bnintendo[-\s]+e[-\s]?shop\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/nintendoeshop.png', FALSE, TRUE),
  ('Game Engines / Frameworks', 'O3DE', 'Games made with Open 3D Engine', '\b(?:o3de|open[-\s]+3d[-\s]+engine)\b', FALSE, 'MEDIUM', FALSE, NULL, TRUE, TRUE),
  ('Music Software', 'OpenMPT', 'Music made with OpenMPT', '\bopen[-\s]?mpt\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/openmpt.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'Phaser', 'Games made with the Phaser framework', '\bphaser(?:\.js)?\b', FALSE, 'MEDIUM', FALSE, NULL, TRUE, TRUE),
  ('Art Software', 'Photoshop', 'Artwork made with Adobe Photoshop', '\b(?:adobe[-\s]+)?photoshop\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/photoshop.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'Pico8', 'For things made in the PICO-8 game engine', '\bpico-?8\b', FALSE, 'HIGH', FALSE, '/images/tags/pico8.png', TRUE, TRUE),
  ('Art', 'PixelArt', NULL, 'pixelart', FALSE, 'HIGH', FALSE, '/images/tags/pixelart.png', TRUE, TRUE),
  ('Art Software', 'Pixelorama', 'Artwork made with Pixelorama', '\bpixelorama\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/pixelorama.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'PlayCanvas', 'Games made with the PlayCanvas engine', '\bplay[-\s]?canvas\b', FALSE, 'MEDIUM', FALSE, NULL, TRUE, TRUE),
  ('Storefronts', 'PlayStationStore', 'Games available through PlayStation Store', '\b(?:playstation|ps)[-\s]+store\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/playstationstore.png', FALSE, TRUE),
  ('General', 'PostMortem', NULL, '\bpost[-\s]?mortem\b', FALSE, 'HIGH', FALSE, '/images/tags/postmortem.png', FALSE, TRUE),
  ('Art Software', 'Procreate', 'Artwork made with Procreate', '\bprocreate\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/procreate.png', TRUE, TRUE),
  ('Music Software', 'ProTools', 'Music made with Pro Tools', '\bpro[-\s]+tools\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/protools.svg', TRUE, TRUE),
  ('Game Engines / Frameworks', 'PuzzleScript', NULL, 'puzzlescript', FALSE, 'HIGH', FALSE, '/images/tags/puzzlescript.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'Pygame', NULL, 'pygame', FALSE, 'HIGH', FALSE, '/images/tags/pygame.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'raylib', 'Games made with the raylib library', '\braylib\b', FALSE, 'MEDIUM', FALSE, NULL, TRUE, TRUE),
  ('Music Software', 'Reaper', 'Music made with REAPER', '\b(?:reaper[-\s]+daw|made[-\s]+(?:in|with)[-\s]+reaper|using[-\s]+reaper)\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/reaper.png', TRUE, TRUE),
  ('Music Software', 'Reason', 'Music made with Reason', '\b(?:reason[-\s]+studios|made[-\s]+(?:in|with)[-\s]+reason|using[-\s]+reason)\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/reason.png', TRUE, TRUE),
  ('Music Software', 'Renoise', 'Music made with Renoise', '\brenoise\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/renoise.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'Renpy', NULL, 'renpy', FALSE, 'HIGH', FALSE, '/images/tags/renpy.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'RPGMaker', NULL, 'rpg[-\s]?maker', FALSE, 'HIGH', FALSE, '/images/tags/rpgmaker.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'Rust', 'For things relating to the rust programming language', 'rust', FALSE, 'HIGH', FALSE, '/images/tag-icons/rust.svg', TRUE, TRUE),
  ('Game Engines / Frameworks', 'Scratch', NULL, 'scratch', FALSE, 'HIGH', FALSE, '/images/tags/scratch.png', TRUE, TRUE),
  ('Development', 'ScreenshotSaturday', NULL, '\b(screenshot[-\s]?saturday|screenshot\s?saturday)\b', FALSE, 'HIGH', FALSE, '/images/tags/saturday.png', FALSE, TRUE),
  ('Art', 'Shaders', NULL, 'shaders?', FALSE, 'HIGH', FALSE, '/images/tags/shaders.png', FALSE, TRUE),
  ('General', 'SiteAnnouncement', 'For official D2Jam site news and announcements', '\b(?:site|d2jam)[-\s]+announcement\b', FALSE, 'HIGH', TRUE, '/images/tags/newspaper.png', FALSE, TRUE),
  ('General', 'SiteChangelog', 'For updates and changes to the D2Jam site', '\b(?:site|d2jam)[-\s]+changelog\b', FALSE, 'HIGH', TRUE, '/images/tags/notebook.png', FALSE, TRUE),
  ('Game Engines / Frameworks', 'Solar2D', 'Games made with the Solar2D engine', '\bsolar[-\s]?2d\b', FALSE, 'MEDIUM', FALSE, NULL, TRUE, TRUE),
  ('Storefronts', 'Steam', NULL, 'steam', FALSE, 'HIGH', FALSE, '/images/tags/steam.png', FALSE, TRUE),
  ('Game Engines / Frameworks', 'Stencyl', NULL, 'stencyl', FALSE, 'HIGH', FALSE, '/images/tags/stencyl.png', TRUE, TRUE),
  ('General', 'Stream', NULL, '\b(?:stream(?:ing|ed|s)?|livestream(?:ing|ed|s)?|live[-\s]+stream(?:ing|ed|s)?)\b', FALSE, 'MEDIUM', FALSE, '/images/tags/stream.png', FALSE, TRUE),
  ('Game Engines / Frameworks', 'Stride', 'Games made with the Stride engine', '\bstride(?:[-\s]+engine)?\b', FALSE, 'MEDIUM', FALSE, NULL, TRUE, TRUE),
  ('Music Software', 'StudioOne', 'Music made with Studio One', '\bstudio[-\s]+one\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/studioone.png', TRUE, TRUE),
  ('Art Software', 'SubstancePainter', 'Artwork made with Adobe Substance 3D Painter', '\b(?:adobe[-\s]+)?substance(?:[-\s]+3d)?[-\s]+painter\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/substancepainter.svg', TRUE, TRUE),
  ('Music Software', 'SunVox', 'Music made with SunVox', '\bsun[-\s]?vox\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/sunvox.png', TRUE, TRUE),
  ('General', 'Teamup', NULL, '\b(team[-\s]?up|teaming\s?up|join\s?forces|join\s?us|work\s?together|collaborate|pair\s?up|group\s?up|partner\s?up)\b', FALSE, 'HIGH', FALSE, '/images/tags/teamup.png', FALSE, TRUE),
  ('General', 'ThemeVote', 'For posts about voting on jam themes', '\btheme[-\s]?votes?\b', FALSE, 'HIGH', FALSE, NULL, FALSE, TRUE),
  ('Game Engines / Frameworks', 'TIC80', NULL, 'tic[-\s]?80', FALSE, 'HIGH', FALSE, '/images/tags/tic80.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'Twine', NULL, 'twine', FALSE, 'HIGH', FALSE, '/images/tags/twine.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'TyranoBuilder', NULL, 'tyranobuilder', FALSE, 'HIGH', FALSE, '/images/tags/tyrano.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'Unity', 'For things made with the Unity game engine', 'unity', FALSE, 'HIGH', FALSE, '/images/tags/unity.png', TRUE, TRUE),
  ('Game Engines / Frameworks', 'UnrealEngine', NULL, 'unreal', FALSE, 'HIGH', FALSE, '/images/tag-icons/unrealengine.svg', TRUE, TRUE),
  ('Storefronts', 'XboxStore', 'Games available through the Xbox Store', '\bxbox[-\s]+store\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/xboxstore.png', FALSE, TRUE),
  ('Art Software', 'ZBrush', 'Artwork made with ZBrush', '\bzbrush\b', FALSE, 'MEDIUM', FALSE, '/images/tag-icons/zbrush.svg', TRUE, TRUE)
) AS taxonomy(
  "category",
  "name",
  "description",
  "autoRegex",
  "alwaysAdded",
  "priority",
  "modOnly",
  "icon",
  "gameTag",
  "postTag"
)
JOIN "TagCategory" AS category ON category."name" = taxonomy."category"
ON CONFLICT ("name") DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('"TagCategory"', 'id'),
  COALESCE((SELECT MAX("id") FROM "TagCategory"), 1),
  TRUE
);

SELECT setval(
  pg_get_serial_sequence('"Tag"', 'id'),
  COALESCE((SELECT MAX("id") FROM "Tag"), 1),
  TRUE
);
