ALTER TABLE "Post"
ADD COLUMN "editedAt" TIMESTAMP(3),
ADD COLUMN "deletedAt" TIMESTAMP(3),
ADD COLUMN "removedAt" TIMESTAMP(3);

ALTER TABLE "Comment"
ADD COLUMN "editedAt" TIMESTAMP(3),
ADD COLUMN "deletedAt" TIMESTAMP(3),
ADD COLUMN "removedAt" TIMESTAMP(3);
