services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 12
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: sleep infinity
volumes:
  postgres_data:
