ALTER TABLE "User"
ADD COLUMN "recommendedGameOverrideIds" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN "recommendedGameHiddenIds" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN "recommendedTrackOverrideIds" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN "recommendedTrackHiddenIds" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[];
